version: '3.3'

services:

  mp-project-backend:
    image: mp-project
    container_name: project-pin
    restart: always
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "8080:8080"
    networks:
      - mp-project-network

volumes:
  mp-project-data:  
    driver: local

networks:
  mp-project-network:
    driver: bridge
